project_name: github binary create
builds:
  - env:
    - CGO_ENABLED=0
  - id: "auth-check"
    main: ./auth-check/auth-check.go
    binary: auth-check
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
  - id: "assignee"
    main: ./assignee/assignee.go
    binary: assignee
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
  - id: "close-pr"
    main: ./close-pr/close-pr.go
    binary: closr-pr
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy
dockers:
-
  ids:
    - "auth-check"
  image_templates:
    - "jackstock8904/auth-check:{{ .Tag}}"
    - "jackstock8904/auth-check:{{ .Version}}"
  use: buildx
  dockerfile: Dockerfile
-
  ids:
    - "assignee"
  image_templates:
    - "jackstock8904/assignee:{{ .Tag}}"
    - "jackstock8904/assignee:{{ .Version}}"
  use: buildx
  dockerfile: Dockerfile
-
  ids:
    - "close-pr"
  image_templates:
    - "jackstock8904/close-pr:{{ .Tag}}"
    - "jackstock8904/close-pr:{{ .Version}}"
  use: buildx
  dockerfile: Dockerfile
