before:
  hooks:
    - go mod download

builds:
  - env:
    - CGO_ENABLED=0

  - id: "github-actions"
    skip: true

  - id: "auth-check"
    dir: auth-check
    binary: auth-check
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
    env:
      - ID=auth-check
      - DOCKERFILE=auth-check/Dockerfile

  - id: "assignee"
    dir: assignee
    binary: assignee
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
    env:
      - ID=assignee
      - DOCKERFILE=assignee/Dockerfile

  - id: "close-pr"
    dir: close-pr
    binary: close-pr
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
    env:
      - ID=close-pr
      - DOCKERFILE=close-pr/Dockerfile

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
-
  ids:
    - "auth-check"
    - "assignee"
    - "close-pr"
  image_templates: [ "jackstock8904/{{ .Env.ID }}:{{ .Tag}}", "jackstock8904/{{ .ENV.ID }}:{{ .Version}}" ]
  dockerfile: '{{ .Env.DOCKERFILE }}'
  use: buildx
