project_name: github binary create
builds:
  - env:
    - CGO_ENABLED=0

  - id: "auth-check"
    main: ./auth-check/auth-check.go
    binary: auth-check
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w

  - id: "assignee"
    main: ./assignee/assignee.go
    binary: assignee
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w

  - id: "close-pr"
    main: ./close-pr/close-pr.go
    binary: close-pr
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
-
  ids:
    - "auth-check"
    - "assignee"
    - "close-pr"
  image_templates: [ "jackstock8904/{{ .Binary}}:{{ .Tag}}", "jackstock8904/{{ .Binary}}:{{ .Version}}" ]
  dockerfile: '{{ .Binary }}/Dockerfile'
  use: buildx
