project_name: assignee
env:
  - CGO_ENABLED=0
  - ID=assignee
  - DOCKERFILE=Dockerfile
  - DIRECTORY=assignee
  - COMMAND=assignee
before:
  hooks:
    - go mod download
builds:
  - dir: assignee
    binary: assignee
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy
dockers:
-
  ids:
    - "assignee"
  image_templates: [ "jackstock8904/{{ .Env.ID }}:{{ .Tag}}", "jackstock8904/{{ .Env.ID }}:{{ .Version}}" ]
  dockerfile: '{{ .Env.DOCKERFILE }}'
  use: buildx
