before:
  hooks:
    - go mod download
builds:
  - id: "auth-check"
    main: auth-check
    binary: auth-check
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
      - ID=auth-check
      - DOCKERFILE=Dockerfile
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy
dockers:
-
  ids:
    - "auth-check"
  image_templates: [ "jackstock8904/{{ .Env.ID }}:{{ .Tag}}", "jackstock8904/{{ .ENV.ID }}:{{ .Version}}" ]
  dockerfile: '{{ .Env.DOCKERFILE }}'
  use: buildx
