project_name: auth-check
env:
  - CGO_ENABLED=0
  - ID={{ .ProjectName }}
  - DOCKERFILE=Dockerfile-goreleaser
  - DIRECTORY=auth-check
  - COMMAND=auth-check
before:
  hooks:
    - go mod download
builds:
  - dir: auth-check
    binary: auth-check
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
    
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy
dockers:
- image_templates: [ "jackstock8904/{{ .Env.ID }}:{{ .Tag}}", "jackstock8904/{{ .Env.ID }}:{{ .Version}}" ]
  dockerfile: '{{ .Env.DOCKERFILE }}'
  use: buildx