project_name: close-pr
env:
  - CGO_ENABLED=0
  - ID=close-pr
  - DOCKERFILE=Dockerfile-goreleaser
  - DIRECTORY=close-pr
before:
  hooks:
    - go mod download
builds:
  - dir: close-pr
    binary: close-pr
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy
dockers:
-
  ids:
    - "close-pr"
  image_templates: [ "jackstock8904/{{ .Env.ID }}:{{ .Tag}}", "jackstock8904/{{ .Env.ID }}:{{ .Version}}" ]
  dockerfile: '{{ .Env.DOCKERFILE }}'
  use: buildx
