name: Nightly Build

on:
  # schedule:
  #   - cron: '00 01 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  version:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Repository Version Check
    outputs:
      version: ${{ steps.version_check.outputs.release_tag }}
    steps:
      - id: version_check
        name: Version check
        uses: docker://jackstock8904/version-check:latest

  docker:
    needs: [check_date, version]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    name: Build container and push to DockerHub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: assignee
            image: jackstock8904/assignee
          - name: auth-check
            image: jackstock8904/auth-check
          - name: close-pr
            image: jackstock8904/close-pr
          - name: version-check
            image: jackstock8904/version-check
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Output
        run: echo ${{ needs.version.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get Tags for Image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ matrix.image }}
          tags: type=semver,suffix=-nightly,pattern={{version}},value=${{ needs.version.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: |
            DIRECTORY=${{ matrix.name }} 
            COMMAND=${{ matrix.name }}
